### ISSUE TITLE
What to do if there's both index.html and index.xhtml

### ISSUE THREAD

**Issue by frivoal** [therealglazou/webbook#1]
The spec says:
> The navigation document MUST be a [html] document named index.html if its serialization is HTML and index.xhtml if its serialization is XML

This doesn't say what it do if the zip file contains both. The decision is fairly arbitrary, but for interoperability, we need to say something. I'd suggest the following addition:

> If both index.html and index.xhtml are present, the User Agent must treat index.html as the navigation document.

**Comment by therealglazou** [comment]
Fully agreed.
