### ISSUE TITLE
what takes priority, index.html or index.xhtml

### ISSUE THREAD

**Issue by akumria** [therealglazou/webbook#14]
In the specification, you indicate that you can transform a webbook into an epub 3.01 document by changing the navigation document from index.html to index.xhtml.

What there be an issue with having *both* index.html and index.xhtml? I'm not sure how strictly conforming epub readers are but perhaps they tolerate html within a xhtml file?

If both files are possible within a webbook, which should take priority?

**Comment by therealglazou** [comment]
@akumria that's already added to the spec: https://github.com/therealglazou/webbook/commit/b18957d417374519378af7595d4cd4deffa536c1
